// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         {children}
//       </body>
//     </html>
//   );
// }

// layout.tsx
// import { Provider } from "react-redux";
// import { PersistGate } from 'redux-persist/integration/react';
// // import { PersistGate } from 'redux-persist/lib/integration/react';
// // import { PersistGate } from "redux-persist/es/integration/react";
// import { store, persistor } from "@/redux/store";
// import { CssBaseline } from "@mui/material";

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <Provider store={store}>
//           <PersistGate loading={null} persistor={persistor}>
//             <CssBaseline />
//             {children}
//           </PersistGate>
//         </Provider>
//       </body>
//     </html>
//   );
// }

// src/app/layout.tsx

import ClientWrapper from "@/components/ClientWrapper"; // Import the client-side wrapper

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>
        {/* Wrap children with the ClientWrapper */}
        <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
};

export default RootLayout;
